---
- name: Deploy Node.js Application
  hosts: webservers
  become: yes # Run tasks with sudo privileges
  vars:
    app_name: nodejs-app
    app_path: /opt/{{ app_name }}
    app_port: 3000
    git_repo_url: "https://github.com/nkefor/my-jenkins-pipeline-app.git" # Your GitHub repo URL
    git_branch: main

  tasks:
    - name: Ensure Node.js and npm are installed (Ubuntu/Debian)
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Node.js and npm are installed (CentOS/RHEL)
      ansible.builtin.yum:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install pm2 globally (process manager)
      ansible.builtin.npm:
        name: pm2
        global: yes
        state: present

    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: directory
        mode: '0755'

    - name: Clone or update application repository
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ app_path }}"
        version: "{{ git_branch }}"
        force: yes # Force update to latest commit

    - name: Install Node.js dependencies
      ansible.builtin.npm:
        path: "{{ app_path }}"
        production: yes # Install only production dependencies

    - name: Start/Restart Node.js application with pm2
      ansible.builtin.command: pm2 restart {{ app_name }} || pm2 start {{ app_path }}/server.js --name {{ app_name }} -- -p {{ app_port }}
      args:
        chdir: "{{ app_path }}"
      changed_when: true # Always report as changed to ensure pm2 command runs

    - name: Save pm2 process list
      ansible.builtin.command: pm2 save
      changed_when: true

    - name: Ensure pm2 starts on boot
      ansible.builtin.command: pm2 startup systemd
      changed_when: true
      # This command generates a systemd unit file. You might need to run it once manually
      # on the target server if it fails due to permissions or environment issues.
