apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-app
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule-app
        image: your-docker-registry/train-schedule-app:latest # Placeholder, Jenkins will replace this
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
--- 
apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
  labels:
    app: train-schedule
spec:
  selector:
    app: train-schedule
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # Use LoadBalancer for external access, or ClusterIP + Ingress
